measure the duration with a monotonic clock
alphasheets-development/dd-trace-hs pull request #1
Opened 2017-08-25 12:45 UTC by zimbatm

This ensures that the measured duration will not be negative due to
system clock adjustements.

2017-08-25 12:46 UTC, zimbatm commented
TODO: Hide the added field in the JSON serialisation

2017-08-25 15:41 UTC, Fuuzetsu requested changes
I suspect the ddog daemon will reject a span with this field so it's not usable out of the box. This field is not needed however if we're okay with a date counted from the end of the trace rather than the beginning.

So: remove `startTime`, put `startTimeMonotonic` in `_span_start`. In `endSpan` take both Realtime and Monotonic values. `_span_duration = realtime_end - (monotonic_end - _span_start)` With this no extra field is needed.

2017-08-25 16:05 UTC, zimbatm commented
@Fuuzetsu like that? ^^ it seems quite hacky to me

2017-08-25 16:15 UTC, Fuuzetsu commented on src/Network/Datadog/Trace.hs
> +               , _span_start_monotonic = fromIntegral $ Clock.toNanoSecs startTimeMonotonic
You forgot to remove this line

2017-08-25 16:16 UTC, Fuuzetsu commented
Yes precisely. It's no more hacky than the previous version, it just inverts which way we're counting from.

2017-08-25 22:24 UTC, zimbatm commented on src/Network/Datadog/Trace.hs
> +               , _span_start_monotonic = fromIntegral $ Clock.toNanoSecs startTimeMonotonic
fixed

2017-08-25 23:52 UTC, Fuuzetsu reviewed
last nitpick: switch curTime and endTime around so we're not measuring the call to getTime for realtime for no reason

2017-08-27 22:46 UTC, zimbatm commented
fixed

2017-08-28 07:44 UTC, merged